//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContext : DbContext
    {
        public DataContext()
            : base("name=DataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblcore_attributes> tblcore_attributes { get; set; }
        public DbSet<tblcore_entities> tblcore_entities { get; set; }
        public DbSet<tblcore_types> tblcore_types { get; set; }
        public DbSet<tbleav_entities> tbleav_entities { get; set; }
        public DbSet<tbleav_entity_attribute> tbleav_entity_attribute { get; set; }
        public DbSet<tbleav_entity_entitytypes> tbleav_entity_entitytypes { get; set; }
        public DbSet<tblpop_order_detail> tblpop_order_detail { get; set; }
        public DbSet<tblbus_address> tblbus_address { get; set; }
        public DbSet<tblbus_business> tblbus_business { get; set; }
        public DbSet<tblcore_entity_types> tblcore_entity_types { get; set; }
        public DbSet<tblcustom_entity> tblcustom_entity { get; set; }
        public DbSet<tbleav_custom_entities> tbleav_custom_entities { get; set; }
        public DbSet<tbleav_entity_attribute_custom> tbleav_entity_attribute_custom { get; set; }
        public DbSet<tblfsk_style> tblfsk_style { get; set; }
        public DbSet<tblfsk_style_sizes> tblfsk_style_sizes { get; set; }
        public DbSet<tblfsk_style_suppliers> tblfsk_style_suppliers { get; set; }
        public DbSet<tblonline_user_map> tblonline_user_map { get; set; }
        public DbSet<tblbus_setvalues> tblbus_setvalues { get; set; }
        public DbSet<tblcustommenu> tblcustommenus { get; set; }
        public DbSet<tblmainmenu> tblmainmenus { get; set; }
        public DbSet<tblsubmenu> tblsubmenus { get; set; }
        public DbSet<aspnetrole> aspnetroles { get; set; }
        public DbSet<aspnetuser> aspnetusers { get; set; }
        public DbSet<tbleav_entity_attribute_value_datetime> tbleav_entity_attribute_value_datetime { get; set; }
        public DbSet<tbleav_entity_attribute_value_decimal> tbleav_entity_attribute_value_decimal { get; set; }
        public DbSet<tbleav_entity_attribute_value_int> tbleav_entity_attribute_value_int { get; set; }
        public DbSet<tbleav_entity_attribute_value_ref> tbleav_entity_attribute_value_ref { get; set; }
        public DbSet<tbleav_entity_attribute_value_varchar> tbleav_entity_attribute_value_varchar { get; set; }
        public DbSet<tbleav_entity_attribute_value_bool> tbleav_entity_attribute_value_bool { get; set; }
        public DbSet<tbleav_entity_attribute_value_orderdetail_ref> tbleav_entity_attribute_value_orderdetail_ref { get; set; }
        public DbSet<tbleav_entity_attribute_value_orderheader_ref> tbleav_entity_attribute_value_orderheader_ref { get; set; }
        public DbSet<tbleav_entity_completed_orderdetail> tbleav_entity_completed_orderdetail { get; set; }
        public DbSet<tbleav_entity_completed_orderheader> tbleav_entity_completed_orderheader { get; set; }
        public DbSet<tbldataannotations_custom> tbldataannotations_custom { get; set; }
        public DbSet<tbldataannotations_master> tbldataannotations_master { get; set; }
        public DbSet<tblpop_despatchnote> tblpop_despatchnote { get; set; }
        public DbSet<tblpop_order_header> tblpop_order_header { get; set; }
        public DbSet<tbleav_email_log> tbleav_email_log { get; set; }
        public DbSet<tblpop_order_color> tblpop_order_color { get; set; }
        public DbSet<tblpop_order_make> tblpop_order_make { get; set; }
        public DbSet<tblpop_order_model> tblpop_order_model { get; set; }
        public DbSet<tbleav_entity_attribute_value> tbleav_entity_attribute_value { get; set; }
    }
}
