//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbus_setvalues
    {
        public string CompanyID { get; set; }
        public string BusinessID { get; set; }
        public string SettingID { get; set; }
        public string Value { get; set; }
    }
}
