//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbus_address
    {
        public string CompanyID { get; set; }
        public string BusinessID { get; set; }
        public int AddressID { get; set; }
        public string Description { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Town { get; set; }
        public string City { get; set; }
        public string Postcode { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> AddressTypeID { get; set; }
        public Nullable<int> ContactID { get; set; }
    }
}
