//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcustom_entity
    {
        public tblcustom_entity()
        {
            this.tbleav_custom_entities = new HashSet<tbleav_custom_entities>();
            this.tblonline_user_map = new HashSet<tblonline_user_map>();
            this.tblcustommenus = new HashSet<tblcustommenu>();
            this.tbldataannotations_custom = new HashSet<tbldataannotations_custom>();
        }
    
        public int ID { get; set; }
        public string ReferenceID { get; set; }
        public Nullable<int> EntityID { get; set; }
    
        public virtual tblbus_business tblbus_business { get; set; }
        public virtual tblcore_entities tblcore_entities { get; set; }
        public virtual ICollection<tbleav_custom_entities> tbleav_custom_entities { get; set; }
        public virtual ICollection<tblonline_user_map> tblonline_user_map { get; set; }
        public virtual ICollection<tblcustommenu> tblcustommenus { get; set; }
        public virtual ICollection<tbldataannotations_custom> tbldataannotations_custom { get; set; }
    }
}
