//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcore_entities
    {
        public tblcore_entities()
        {
            this.tblcore_types = new HashSet<tblcore_types>();
            this.tblcore_entity_types = new HashSet<tblcore_entity_types>();
            this.tblcustom_entity = new HashSet<tblcustom_entity>();
            this.tbleav_entities = new HashSet<tbleav_entities>();
        }
    
        public int ID { get; set; }
        public string description { get; set; }
        public string Notification { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    
        public virtual ICollection<tblcore_types> tblcore_types { get; set; }
        public virtual ICollection<tblcore_entity_types> tblcore_entity_types { get; set; }
        public virtual ICollection<tblcustom_entity> tblcustom_entity { get; set; }
        public virtual ICollection<tbleav_entities> tbleav_entities { get; set; }
    }
}
