//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldataannotations_custom
    {
        public int ID { get; set; }
        public Nullable<int> CustomEntityID { get; set; }
        public string DisplayText { get; set; }
        public bool IsRequired { get; set; }
        public Nullable<int> DAID { get; set; }
        public string ErrorMessage { get; set; }
    
        public virtual tblcustom_entity tblcustom_entity { get; set; }
        public virtual tbldataannotations_master tbldataannotations_master { get; set; }
    }
}
