//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldataannotations_master
    {
        public tbldataannotations_master()
        {
            this.tbldataannotations_custom = new HashSet<tbldataannotations_custom>();
        }
    
        public int ID { get; set; }
        public string OrgText { get; set; }
        public bool IsRequired { get; set; }
        public string ErrorMessage { get; set; }
    
        public virtual ICollection<tbldataannotations_custom> tbldataannotations_custom { get; set; }
    }
}
