//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbleav_custom_entities
    {
        public tbleav_custom_entities()
        {
            this.IsmailReq = false;
            this.IsHeader = false;
            this.IsDespatchType = false;
            this.IsDocument = false;
            this.tbleav_entity_attribute_custom = new HashSet<tbleav_entity_attribute_custom>();
            this.tbleav_entity_completed_orderdetail = new HashSet<tbleav_entity_completed_orderdetail>();
            this.tbleav_entity_completed_orderheader = new HashSet<tbleav_entity_completed_orderheader>();
            this.tbleav_entity_attribute_value_ref = new HashSet<tbleav_entity_attribute_value_ref>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CustomEntityID { get; set; }
        public string description { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public bool IsmailReq { get; set; }
        public bool IsHeader { get; set; }
        public bool IsDespatchType { get; set; }
        public Nullable<bool> IsDocument { get; set; }
    
        public virtual tblcustom_entity tblcustom_entity { get; set; }
        public virtual ICollection<tbleav_entity_attribute_custom> tbleav_entity_attribute_custom { get; set; }
        public virtual ICollection<tbleav_entity_completed_orderdetail> tbleav_entity_completed_orderdetail { get; set; }
        public virtual ICollection<tbleav_entity_completed_orderheader> tbleav_entity_completed_orderheader { get; set; }
        public virtual ICollection<tbleav_entity_attribute_value_ref> tbleav_entity_attribute_value_ref { get; set; }
    }
}
