//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbleav_entity_entitytypes
    {
        public int ID { get; set; }
        public Nullable<int> eav_entity_id { get; set; }
        public Nullable<int> type_id { get; set; }
    
        public virtual tblcore_types tblcore_types { get; set; }
        public virtual tbleav_entities tbleav_entities { get; set; }
    }
}
