//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbleav_entity_attribute_value_ref
    {
        public tbleav_entity_attribute_value_ref()
        {
            this.tbleav_entity_attribute_value_datetime = new HashSet<tbleav_entity_attribute_value_datetime>();
            this.tbleav_entity_attribute_value_decimal = new HashSet<tbleav_entity_attribute_value_decimal>();
            this.tbleav_entity_attribute_value_int = new HashSet<tbleav_entity_attribute_value_int>();
            this.tbleav_entity_attribute_value_varchar = new HashSet<tbleav_entity_attribute_value_varchar>();
            this.tbleav_entity_attribute_value_bool = new HashSet<tbleav_entity_attribute_value_bool>();
            this.tbleav_entity_attribute_value_orderdetail_ref = new HashSet<tbleav_entity_attribute_value_orderdetail_ref>();
            this.tbleav_entity_attribute_value_orderheader_ref = new HashSet<tbleav_entity_attribute_value_orderheader_ref>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Username { get; set; }
        public int EntityID { get; set; }
    
        public virtual ICollection<tbleav_entity_attribute_value_datetime> tbleav_entity_attribute_value_datetime { get; set; }
        public virtual ICollection<tbleav_entity_attribute_value_decimal> tbleav_entity_attribute_value_decimal { get; set; }
        public virtual ICollection<tbleav_entity_attribute_value_int> tbleav_entity_attribute_value_int { get; set; }
        public virtual ICollection<tbleav_entity_attribute_value_varchar> tbleav_entity_attribute_value_varchar { get; set; }
        public virtual ICollection<tbleav_entity_attribute_value_bool> tbleav_entity_attribute_value_bool { get; set; }
        public virtual ICollection<tbleav_entity_attribute_value_orderdetail_ref> tbleav_entity_attribute_value_orderdetail_ref { get; set; }
        public virtual ICollection<tbleav_entity_attribute_value_orderheader_ref> tbleav_entity_attribute_value_orderheader_ref { get; set; }
        public virtual tbleav_custom_entities tbleav_custom_entities { get; set; }
    }
}
