//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbleav_entity_attribute_value_datetime
    {
        public int ID { get; set; }
        public Nullable<int> RefID { get; set; }
        public Nullable<int> eav_entity_attribute_id { get; set; }
        public Nullable<System.DateTime> Value { get; set; }
    
        public virtual tbleav_entity_attribute_custom tbleav_entity_attribute_custom { get; set; }
        public virtual tbleav_entity_attribute_value_ref tbleav_entity_attribute_value_ref { get; set; }
    }
}
