//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbleav_entities
    {
        public tbleav_entities()
        {
            this.tbleav_entity_attribute = new HashSet<tbleav_entity_attribute>();
            this.tbleav_entity_entitytypes = new HashSet<tbleav_entity_entitytypes>();
        }
    
        public int ID { get; set; }
        public string description { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public Nullable<int> coreentity_id { get; set; }
        public bool IsmailReq { get; set; }
        public Nullable<bool> IsHeader { get; set; }
    
        public virtual ICollection<tbleav_entity_attribute> tbleav_entity_attribute { get; set; }
        public virtual ICollection<tbleav_entity_entitytypes> tbleav_entity_entitytypes { get; set; }
        public virtual tblcore_entities tblcore_entities { get; set; }
    }
}
