//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbleav_entity_attribute_value_orderheader_ref
    {
        public int ID { get; set; }
        public int RefID { get; set; }
        public int OrderNo { get; set; }
        public string CompanyID { get; set; }
        public string WareHouseID { get; set; }
    
        public virtual tbleav_entity_attribute_value_ref tbleav_entity_attribute_value_ref { get; set; }
        public virtual tblpop_order_header tblpop_order_header { get; set; }
    }
}
