//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbleav_entity_attribute
    {
        public int ID { get; set; }
        public Nullable<int> entity_id { get; set; }
        public Nullable<int> attribute_id { get; set; }
        public string entity_attribute_value { get; set; }
    
        public virtual tblcore_attributes tblcore_attributes { get; set; }
        public virtual tbleav_entities tbleav_entities { get; set; }
    }
}
