//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfsk_style_sizes
    {
        public string CompanyID { get; set; }
        public string StyleID { get; set; }
        public string SizeID { get; set; }
        public Nullable<short> SeqNo { get; set; }
        public Nullable<short> VATCode { get; set; }
        public int PriceOptionID { get; set; }
        public string StockingType { get; set; }
        public bool IsStatic { get; set; }
    }
}
