//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfsk_style
    {
        public string CompanyID { get; set; }
        public string StyleID { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public Nullable<short> Bundle { get; set; }
        public Nullable<int> Product_Group { get; set; }
        public Nullable<int> Product_Group_Sub { get; set; }
        public Nullable<double> Weight { get; set; }
        public string SupplimentaryUnits { get; set; }
        public Nullable<int> Issue_Type { get; set; }
        public Nullable<int> Issue_Units { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<short> Maxsize { get; set; }
        public Nullable<short> Maxcol { get; set; }
        public Nullable<short> Maxop { get; set; }
        public Nullable<short> Maxmat { get; set; }
        public Nullable<double> Overhead { get; set; }
        public Nullable<double> Yield { get; set; }
        public Nullable<double> Waste { get; set; }
        public Nullable<double> Allowance { get; set; }
        public string Nominal_Code { get; set; }
        public string Commodity_Code { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Season { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> Obsolete_Class { get; set; }
        public bool Live { get; set; }
        public string StyleImage { get; set; }
        public bool BatchControl { get; set; }
        public Nullable<int> StockingUOM { get; set; }
        public Nullable<int> IssueUOM { get; set; }
        public string StockingType { get; set; }
        public string Country { get; set; }
    }
}
