//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfsk_style_suppliers
    {
        public string CompanyID { get; set; }
        public string SupplierID { get; set; }
        public string StyleID { get; set; }
        public string SupplierProd_code { get; set; }
        public Nullable<int> Supplier_price { get; set; }
        public Nullable<short> SupplierSeq { get; set; }
        public string SizeID { get; set; }
        public Nullable<int> Leadtime { get; set; }
        public string WarehouseID { get; set; }
        public Nullable<int> IsBulkOrder { get; set; }
    
        public virtual tblbus_business tblbus_business { get; set; }
    }
}
