//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblonline_user_map
    {
        public string Username { get; set; }
        public int CustomEntityID { get; set; }
    
        public virtual tblcustom_entity tblcustom_entity { get; set; }
    }
}
