//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpop_order_header_status
    {
        public string CompanyId { get; set; }
        public string WareHouseId { get; set; }
        public int OrderNo { get; set; }
        public int StatusID { get; set; }
        public int UserID { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual tblpop_customer_status tblpop_customer_status { get; set; }
        public virtual tblpop_order_header tblpop_order_header { get; set; }
    }
}
