//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpop_customer_status
    {
        public tblpop_customer_status()
        {
            this.tblpop_order_header_status = new HashSet<tblpop_order_header_status>();
        }
    
        public int StatusID { get; set; }
        public string SupplierID { get; set; }
        public string StatusDesc { get; set; }
        public Nullable<int> PriorityID { get; set; }
    
        public virtual ICollection<tblpop_order_header_status> tblpop_order_header_status { get; set; }
    }
}
