//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpop_order_make
    {
        public tblpop_order_make()
        {
            this.tblpop_order_model = new HashSet<tblpop_order_model>();
        }
    
        public int id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tblpop_order_model> tblpop_order_model { get; set; }
    }
}
