//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpop_order_detail
    {
        public tblpop_order_detail()
        {
            this.tbleav_entity_attribute_value_orderdetail_ref = new HashSet<tbleav_entity_attribute_value_orderdetail_ref>();
            this.tbleav_entity_completed_orderdetail = new HashSet<tbleav_entity_completed_orderdetail>();
        }
    
        public string CompanyId { get; set; }
        public string WareHouseId { get; set; }
        public int OrderNo { get; set; }
        public int LineNo { get; set; }
        public Nullable<short> LineType { get; set; }
        public string StyleID { get; set; }
        public string ColourID { get; set; }
        public string SizeID { get; set; }
        public Nullable<int> UnitOfIssue { get; set; }
        public Nullable<int> TypeOfIssue { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> OrdQty { get; set; }
        public Nullable<int> AllQty { get; set; }
        public Nullable<int> InvQty { get; set; }
        public Nullable<int> DespQty { get; set; }
        public Nullable<decimal> CommissionRate { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<short> VatCode { get; set; }
        public string NomCode { get; set; }
        public Nullable<int> Currency_Exchange_Rate { get; set; }
        public Nullable<int> SalesOrderNo { get; set; }
        public Nullable<int> SOLineNo { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string FreeTextType { get; set; }
        public string FreeText { get; set; }
        public Nullable<int> OutStandingQty { get; set; }
        public Nullable<int> IssueUOM { get; set; }
        public Nullable<int> IssueQty { get; set; }
        public Nullable<int> StockingUOM { get; set; }
        public Nullable<int> OriginalLineNo { get; set; }
        public Nullable<int> JobSheetNo { get; set; }
        public Nullable<int> JobSheetLineNo { get; set; }
        public Nullable<int> AssemblyID { get; set; }
        public Nullable<int> AsmLineNo { get; set; }
    
        public virtual ICollection<tbleav_entity_attribute_value_orderdetail_ref> tbleav_entity_attribute_value_orderdetail_ref { get; set; }
        public virtual ICollection<tbleav_entity_completed_orderdetail> tbleav_entity_completed_orderdetail { get; set; }
        public virtual tblpop_order_header tblpop_order_header { get; set; }
    }
}
