//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpop_order_header
    {
        public tblpop_order_header()
        {
            this.tblpop_order_detail = new HashSet<tblpop_order_detail>();
            this.tbleav_entity_completed_orderheader = new HashSet<tbleav_entity_completed_orderheader>();
            this.tbleav_entity_attribute_value_orderheader_ref = new HashSet<tbleav_entity_attribute_value_orderheader_ref>();
        }
    
        public string CompanyId { get; set; }
        public string WareHouseId { get; set; }
        public int OrderNo { get; set; }
        public string SuppID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string InvDesc { get; set; }
        public string InvAddress1 { get; set; }
        public string InvAddress2 { get; set; }
        public string InvAddress3 { get; set; }
        public string InvCity { get; set; }
        public string InvTown { get; set; }
        public string InvPostCode { get; set; }
        public string InvCountry { get; set; }
        public string DelDesc { get; set; }
        public string DelAddress1 { get; set; }
        public string DelAddress2 { get; set; }
        public string DelAddress3 { get; set; }
        public string DelCity { get; set; }
        public string DelTown { get; set; }
        public string DelPostCode { get; set; }
        public string DelCountry { get; set; }
        public string OurRef { get; set; }
        public string YourRef { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public string Carrier { get; set; }
        public Nullable<decimal> CarrierCharge { get; set; }
        public Nullable<double> CustDisc { get; set; }
        public Nullable<double> SettDisc { get; set; }
        public Nullable<double> VolDisc { get; set; }
        public string RepNo { get; set; }
        public Nullable<short> SettlementDays { get; set; }
        public bool OrderConfirm { get; set; }
        public string CommentsExternal { get; set; }
        public bool Printed { get; set; }
        public string SalesOrderNo { get; set; }
        public bool Cancelled { get; set; }
        public bool Completed { get; set; }
        public Nullable<int> CalendarPeriod { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<double> Total { get; set; }
        public string UserID { get; set; }
        public string OrderType { get; set; }
        public bool AllowAllocation { get; set; }
        public Nullable<bool> ReqBOM { get; set; }
        public Nullable<bool> IsPrepaid { get; set; }
        public string CustID { get; set; }
        public string CustRef { get; set; }
        public string DispatchMode { get; set; }
        public Nullable<int> DispatchLeadTime { get; set; }
        public Nullable<System.DateTime> EXWDate { get; set; }
    
        public virtual ICollection<tblpop_order_detail> tblpop_order_detail { get; set; }
        public virtual ICollection<tbleav_entity_completed_orderheader> tbleav_entity_completed_orderheader { get; set; }
        public virtual ICollection<tbleav_entity_attribute_value_orderheader_ref> tbleav_entity_attribute_value_orderheader_ref { get; set; }
        public virtual tblbus_business tblbus_business { get; set; }
    }
}
