//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsubmenu
    {
        public int ID { get; set; }
        public Nullable<int> MainID { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<bool> ISLoginReq { get; set; }
        public Nullable<int> SeqNo { get; set; }
    
        public virtual tblmainmenu tblmainmenu { get; set; }
    }
}
